App\Entity\Location:   
    properties:
        city:
          - NotBlank: ~
            groups: ['edit', 'new']
        latitude:
            - Range:
                min: -90
                max: 90
                groups: ['edit', 'new']
        longitude:
            - Range:
                min: -180
                max: 180
                groups: ['edit', 'new']

App\Entity\Measurement:
    properties:
        celsius:
            - Range:
                min: -40
                max: 60
                groups: ['edit', 'new']
        atmosferic_pressure:
            -  Range: 
                min: 900
                max: 1200
                groups: ['edit', 'new']
        rain_drop:
            -  Range:
                min: 0
                max: 100
                groups: ['edit', 'new']
