weather_in_city:
  path: "/weather"
  controller: App\Controller\WeatherController:cityAction
  requirements:
    city: \d+

location:
  path: /location
  prefix: "location"

measurement:
  path: /measurement
  prefix: "measurement"

login:
  path: "/login"
  controller: App\Controller\LoginController:index

app_logout:
  path: /logout
  methods: GET