weather_in_city:
  path: /weather/{country}/{city}
  controller: App\Controller\WeatherController:cityAction

app_weather_api:
  path: /weather/api
  controller: App\Controller\WeatherApiController:cityAction
  
location:
  path: /location
  prefix: "location"

measurement:
  path: /measurement
  prefix: "measurement"

login:
  path: "/login"
  controller: App\Controller\LoginController:index

app_logout:
  path: /logout
  methods: GET